// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWEnaT0dt9pamuZXVnZEcI49IpxF8IvJo',
    appId: '1:1045831384770:web:c1330bd3bb01968c11455b',
    messagingSenderId: '1045831384770',
    projectId: 'mirrorfly-uikit-dev',
    authDomain: 'mirrorfly-uikit-dev.firebaseapp.com',
    storageBucket: 'mirrorfly-uikit-dev.appspot.com',
    measurementId: 'G-SP1SE77CZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfG5u1-XDZhWD8vOZGK5hTKyqsVOjHSSM',
    appId: '1:1045831384770:android:cfdf83b6e0ada96911455b',
    messagingSenderId: '1045831384770',
    projectId: 'mirrorfly-uikit-dev',
    storageBucket: 'mirrorfly-uikit-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy7JDQj6Ar03dMXFCQ-SHgBdBPnKAteG4',
    appId: '1:1045831384770:ios:eff2902ecda09bf911455b',
    messagingSenderId: '1045831384770',
    projectId: 'mirrorfly-uikit-dev',
    storageBucket: 'mirrorfly-uikit-dev.appspot.com',
    androidClientId: '1045831384770-aa561p9dbh0467tsg3395ufeleu162k4.apps.googleusercontent.com',
    iosClientId: '1045831384770-a90apqltl7dtlbaj4844235jgv8l1hfm.apps.googleusercontent.com',
    iosBundleId: 'com.mirrorfly.uikitflutter.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy7JDQj6Ar03dMXFCQ-SHgBdBPnKAteG4',
    appId: '1:1045831384770:ios:8e3466b1aa07bd5811455b',
    messagingSenderId: '1045831384770',
    projectId: 'mirrorfly-uikit-dev',
    storageBucket: 'mirrorfly-uikit-dev.appspot.com',
    androidClientId: '1045831384770-aa561p9dbh0467tsg3395ufeleu162k4.apps.googleusercontent.com',
    iosClientId: '1045831384770-od86edts5jinp5fg6e1t7qkf707rugrm.apps.googleusercontent.com',
    iosBundleId: 'com.contusdemo.mirrorFlyDemo',
  );
}
