# Uncomment this line to define a global platform for your project
platform :ios, '12.1'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

use_frameworks!

target 'Runner' do
  
  use_modular_headers!

#   pod 'libPhoneNumber-iOS'
#   pod 'Alamofire'
#   pod 'RealmSwift', '10.20.1'
#   pod 'XMPPFramework/Swift'
#   pod 'SocketRocket'
#   pod 'Socket.IO-Client-Swift'
#   pod 'GoogleWebRTC'
#  pod 'Mirrorfly-ios-framework', :git => 'https://github.com/MirrorFly/Mirrorfly-ios-framework.git', :branch => 'pod_qa'
#  pod 'Mirrorfly-ios-framework', :git => 'https://github.com/MirrorFly/Mirrorfly-ios-framework.git', :branch => 'qa'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

#def notification_pods
#
##  pod 'Mirrorfly-ios-framework', :git => 'https://github.com/MirrorFly/Mirrorfly-ios-framework.git', :tag => '0.0.5'
#  pod 'libPhoneNumber-iOS' #, '~> 0.8'
#   pod 'Alamofire' #, '~> 5.3'
#    #Pods for FlyCall
#   pod 'SocketRocket'
#   pod 'Socket.IO-Client-Swift' # To communicte Socket I/O server
#   pod 'GoogleWebRTC' # WebRTC for Calls
#   pod 'RealmSwift', '10.20.1'
#   pod 'XMPPFramework/Swift'
##  pod 'Mirrorfly-ios-framework', :git => 'https://github.com/MirrorFly/Mirrorfly-ios-framework.git', :branch => 'master'
##  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
#
#
#end
#
#target 'FlutterNotificationExtnsion' do
#  notification_pods
#end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#       flutter_additional_ios_build_settings(target)
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
              '$(inherited)',
        ## dart: PermissionGroup.contacts
        'PERMISSION_CONTACTS=1',
        'PERMISSION_LOCATION=1',
        'PERMISSION_PHOTOS=1',
        #'PERMISSION_MICROPHONE=1',
        'PERMISSION_CAMERA=1',
      ## dart: PermissionGroup.mediaLibrary
        'PERMISSION_MEDIA_LIBRARY=1',
      ]
#      for build Archive issues in Xocde 14.3
      shell_script_path = "Pods/Target Support Files/#{target.name}/#{target.name}-frameworks.sh"
            if File::exist?(shell_script_path)
              shell_script_input_lines = File.readlines(shell_script_path)
              shell_script_output_lines = shell_script_input_lines.map { |line| line.sub("source=\"$(readlink \"${source}\")\"", "source=\"$(readlink -f \"${source}\")\"") }
              File.open(shell_script_path, 'w') do |f|
                shell_script_output_lines.each do |line|
                  f.write line
                end
              end
            end
#       for build Archive issues in Xocde 14.3
     end
  end
end
