# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

# Changelogs Filepath
changelogs = File.read("../changelogs.txt")

desc "Cleans Build, Generate IPA for QA, Upload IPA to Firebase with QA Release Notes and distributes to testers, Move IPA to Artifact folder"
  lane :qa_firebase do
	clean_build_artifacts
	build_app(scheme: "Runner",
	    export_options: "JenkinsPlist/FlutterQa.plist",
	    export_method: "ad-hoc"
	)
	firebase_app_distribution(
		app: "1:235373697524:ios:2d40908026b55394a0c1a1",
		groups: "MirrorFlyQA",
		release_notes: changelogs,
		firebase_cli_path: "/usr/local/bin/firebase",
		firebase_cli_token: "1//0g53oUKW5j5bJCgYIARAAGBASNwF-L9Ir7Ei_6NzWEsyHOMMXytlesfgXShhLeJWRwbcf2MC3e7BaC5dwYlUZB-_osuQFsxy0Du0"
	)
		IPA_LOCATION = "#{lane_context[SharedValues::IPA_OUTPUT_PATH]}" 
		copy_artifacts(
   		artifacts: [IPA_LOCATION],
		keep_original: false
		)
end

end
